# Generated by Django 5.2.6 on 2025-10-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vetis_login',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='логин Ветис'),
        ),
    ]
