# Generated by Django 5.2.6 on 2025-09-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VetisCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField()),
                ('password', models.CharField()),
                ('api_key', models.CharField()),
                ('service_id', models.CharField()),
                ('issuer_id', models.CharField()),
            ],
        ),
    ]
