# Generated by Django 5.2.6 on 2025-09-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vetiscredentials',
            options={'ordering': ['name'], 'verbose_name': 'подключение Ветис', 'verbose_name_plural': 'подключения Ветис'},
        ),
        migrations.AddField(
            model_name='vetiscredentials',
            name='is_productive',
            field=models.BooleanField(default=False, verbose_name='продуктивный'),
        ),
        migrations.AlterField(
            model_name='vetiscredentials',
            name='api_key',
            field=models.CharField(verbose_name='API key'),
        ),
        migrations.AlterField(
            model_name='vetiscredentials',
            name='issuer_id',
            field=models.CharField(verbose_name='issuer ID'),
        ),
        migrations.AlterField(
            model_name='vetiscredentials',
            name='login',
            field=models.CharField(verbose_name='логин'),
        ),
        migrations.AlterField(
            model_name='vetiscredentials',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='vetiscredentials',
            name='password',
            field=models.CharField(verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='vetiscredentials',
            name='service_id',
            field=models.CharField(verbose_name='service ID'),
        ),
    ]
