# Generated by Django 5.2.6 on 2025-09-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0002_alter_vetiscredentials_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(unique=True)),
                ('uuid', models.UUIDField(unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Юрлицо'), (2, 'Физлицо'), (3, 'ИП')], verbose_name='тип')),
                ('name', models.CharField(verbose_name='имя')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'хозяйствующий субъект',
                'verbose_name_plural': 'хозяйствующие субъекты',
                'ordering': ['name'],
            },
        ),
    ]
