# Generated by Django 5.2.6 on 2025-09-30 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0003_businessentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='метка времени')),
                ('soap_action', models.CharField(max_length=30, null=True, verbose_name='SOAP action')),
                ('soap_request', models.TextField(null=True, verbose_name='текст запроса')),
                ('response_status_code', models.IntegerField(null=True, verbose_name='статус ответа')),
                ('response_body', models.TextField(null=True, verbose_name='текст ответа')),
                ('comment', models.CharField(max_length=255, null=True, verbose_name='комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'запись истории запросов',
                'verbose_name_plural': 'записи истории запросов',
                'ordering': ['-datetime'],
            },
        ),
    ]
