# Generated by Django 5.2.6 on 2025-10-01 08:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0004_apirequestshistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiRequestsHistory',
            new_name='ApiRequestsHistoryRecord',
        ),
    ]
