# Generated by Django 5.2.6 on 2025-10-01 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0006_alter_apirequestshistoryrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessentity',
            name='credentials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vetis_api.vetiscredentials', verbose_name='параметры подключения'),
        ),
    ]
