# Generated by Django 5.2.6 on 2025-10-01 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0007_businessentity_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField()),
                ('uuid', models.UUIDField()),
                ('type', models.IntegerField(choices=[(1, 'предприятие'), (2, 'рынок'), (3, 'СББЖ'), (4, 'судно')], verbose_name='тип')),
                ('name', models.CharField(verbose_name='имя')),
                ('number_list', models.CharField(blank=True, null=True, verbose_name='номера предприятия')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес')),
                ('business_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vetis_api.businessentity')),
            ],
            options={
                'verbose_name': 'предприятие',
                'verbose_name_plural': 'предприятия',
                'ordering': ['name'],
            },
        ),
    ]
