# Generated by Django 5.2.6 on 2025-10-02 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0008_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessentity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активно'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='business_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vetis_api.businessentity', verbose_name='хозяйствующий субъект'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='guid',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
