# Generated by Django 5.2.6 on 2025-10-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0009_businessentity_is_active_enterprise_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessentity',
            name='guid',
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='guid',
            field=models.UUIDField(db_index=True, unique=True),
        ),
    ]
