# Generated by Django 5.2.6 on 2025-10-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0010_alter_businessentity_guid_alter_enterprise_guid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, unique=True)),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='код ТН ВЭД')),
                ('product_type', models.IntegerField(choices=[(1, 'Мясо и мясопродукты'), (2, 'Корма и кормовые добавки'), (3, 'Живые животные'), (4, 'Лекарственные средства'), (5, 'Пищевые продукты'), (6, 'Непищевые продукты и другое'), (7, 'Рыба и морепродукты'), (8, 'Продукция, не требующая разрешения')], verbose_name='тип продукции')),
            ],
            options={
                'verbose_name': 'продукция',
                'verbose_name_plural': 'продукция',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='businessentity',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessentity',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessentity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='number_list',
            field=models.CharField(blank=True, default='', verbose_name='номера предприятия'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, unique=True)),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='код ТН ВЭД')),
                ('product_guid', models.UUIDField(verbose_name='продукция (GUID)')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vetis_api.product', verbose_name='продукция')),
            ],
            options={
                'verbose_name': 'вид продукции',
                'verbose_name_plural': 'виды продукции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, unique=True)),
                ('uuid', models.UUIDField(unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('gtin', models.CharField(blank=True, max_length=20, verbose_name='название')),
                ('product_type', models.IntegerField(choices=[(1, 'Мясо и мясопродукты'), (2, 'Корма и кормовые добавки'), (3, 'Живые животные'), (4, 'Лекарственные средства'), (5, 'Пищевые продукты'), (6, 'Непищевые продукты и другое'), (7, 'Рыба и морепродукты'), (8, 'Продукция, не требующая разрешения')], verbose_name='тип продукции')),
                ('product_guid', models.UUIDField(verbose_name='продукция (GUID)')),
                ('subproduct_guid', models.UUIDField(verbose_name='вид продукции (GUID)')),
                ('is_gost', models.BooleanField(default=False, verbose_name='соответствует ГОСТ')),
                ('gost', models.CharField(blank=True, max_length=255, verbose_name='ГОСТ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vetis_api.product', verbose_name='продукция')),
                ('subproduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vetis_api.subproduct', verbose_name='вид продукции')),
            ],
            options={
                'verbose_name': 'наименование продукции',
                'verbose_name_plural': 'наименования продукции',
                'ordering': ['name'],
            },
        ),
    ]
