# Generated by Django 5.2.6 on 2025-10-17 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0011_product_alter_businessentity_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vetis_api.businessentity', verbose_name='производитель'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='producer_guid',
            field=models.UUIDField(default='29910ac0-0d3a-4477-bb8d-2c1ddd5f7311', verbose_name='производитель (GUID)'),
            preserve_default=False,
        ),
    ]
