# Generated by Django 5.2.6 on 2025-10-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0012_productitem_producer_productitem_producer_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessentity',
            name='short_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='имя (кратко)'),
        ),
    ]
