# Generated by Django 5.2.6 on 2025-10-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0013_businessentity_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='gtin',
            field=models.CharField(blank=True, max_length=20, verbose_name='GTIN'),
        ),
    ]
