# Generated by Django 5.2.6 on 2025-10-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0015_packingtype_unit_stockentry_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packingtype',
            old_name='globalID',
            new_name='global_id',
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='entry_number',
            field=models.BigIntegerField(verbose_name='номер записи'),
        ),
    ]
