# Generated by Django 5.2.6 on 2025-10-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0016_rename_globalid_packingtype_global_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingtype',
            name='global_id',
            field=models.CharField(max_length=2, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='packingtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='идентификатор'),
        ),
    ]
