# Generated by Django 5.2.6 on 2025-10-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0018_alter_packingtype_global_id_alter_packingtype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockentry',
            options={'ordering': ['-date_updated'], 'verbose_name': 'запись складского журнала', 'verbose_name_plural': 'записи складского журнала'},
        ),
    ]
