# Generated by Django 5.2.6 on 2025-10-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0019_alter_stockentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='stock_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetis_api.stockentry', verbose_name='запись журнала'),
        ),
    ]
