# Generated by Django 5.2.6 on 2025-10-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0020_alter_package_stock_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='producer_guid',
            field=models.UUIDField(blank=True, null=True, verbose_name='производитель (GUID)'),
        ),
    ]
