# Generated by Django 5.2.6 on 2025-10-27 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0021_alter_productitem_producer_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='stock_entries_last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последнее обновление журнала'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producer_set', to='vetis_api.enterprise', verbose_name='предприятие-производитель'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='producer_guid',
            field=models.UUIDField(blank=True, null=True, verbose_name='предприятие-производитель (GUID)'),
        ),
    ]
