# Generated by Django 5.2.6 on 2025-10-27 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0022_enterprise_stock_entries_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produced_entries_set', to='vetis_api.enterprise', verbose_name='предприятие-производитель'),
        ),
    ]
