# Generated by Django 5.2.6 on 2025-10-28 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0023_alter_stockentry_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntryVetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetis_api.stockentry', verbose_name='запись журнала')),
            ],
            options={
                'verbose_name': 'вет. документ',
                'verbose_name_plural': 'вет. документы',
            },
        ),
    ]
