# Generated by Django 5.2.6 on 2025-10-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0024_stockentryvetdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_entry_guid', models.UUIDField(unique=True, verbose_name='GUID записи журнала')),
                ('important', models.BooleanField(verbose_name='важно')),
                ('text', models.CharField(max_length=255, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'комментарий записи журнала',
                'verbose_name_plural': 'комментарии записи журнала',
            },
        ),
    ]
