# Generated by Django 5.2.6 on 2025-11-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0025_stockentrycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='is_allowed',
            field=models.BooleanField(default=False, verbose_name='разрешено работать через АПИ'),
        ),
        migrations.AlterField(
            model_name='stockentrycomment',
            name='stock_entry_guid',
            field=models.UUIDField(db_index=True, unique=True, verbose_name='GUID записи журнала'),
        ),
    ]
