# Generated by Django 5.2.6 on 2025-11-04 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0026_enterprise_is_allowed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntryMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True)),
                ('is_populated', models.BooleanField(default=False, verbose_name='данные заполнены')),
                ('initial_status', models.IntegerField(choices=[(100, 'Запись создана'), (101, 'Гашение ВС (импорт)'), (102, 'Гашение ВСД'), (103, 'Производство'), (104, 'Справка о здоровье дойных животных'), (105, 'Аннулирование ВСД или транзакции'), (106, 'Гашение бумажного ВСД'), (110, 'Объединение'), (120, 'Разделение'), (200, 'Внесены изменения'), (201, 'Запись аннулирована'), (202, 'Списание'), (203, 'Редактирование производства'), (204, 'Заключение по результатам ВСЭ'), (230, 'Обновление в результате присоединения'), (231, 'Обновление в результате присоединения'), (240, 'Обновление в результате отделения'), (250, 'Восстановление после удаления'), (260, 'Пометка на удаление'), (300, 'Перемещение в другую группу'), (400, 'Запись удалена'), (410, 'Удаление в результате объединения'), (420, 'Удаление в результате разделения'), (430, 'Удаление в результате присоединения')], verbose_name='статус версии')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='дата создания')),
                ('initial_volume', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='объем')),
                ('source', models.TextField(blank=True, max_length=255, verbose_name='источник возникновения')),
            ],
            options={
                'verbose_name': 'головная запись складского журнала',
                'verbose_name_plural': 'головные записи складского журнала',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='stockentry',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vetis_api.stockentrymain', verbose_name='головная запись'),
        ),
    ]
