# Generated by Django 5.2.6 on 2025-11-04 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0028_alter_stockentrymain_guid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vetis_api.stockentrymain', verbose_name='головная запись'),
        ),
    ]
