# Generated by Django 5.2.6 on 2025-11-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0029_alter_stockentry_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentrymain',
            name='source',
        ),
        migrations.AddField(
            model_name='stockentrymain',
            name='comment_important',
            field=models.BooleanField(default=False, verbose_name='комментарий важен'),
        ),
        migrations.AddField(
            model_name='stockentrymain',
            name='comment_text',
            field=models.TextField(blank=True, max_length=255, verbose_name='текст комментария'),
        ),
        migrations.AddField(
            model_name='stockentrymain',
            name='source_be_guid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='stockentrymain',
            name='source_be_name',
            field=models.TextField(blank=True, max_length=255, verbose_name='хозяйствующий субъект - источник'),
        ),
        migrations.AddField(
            model_name='stockentrymain',
            name='source_ent_guid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='stockentrymain',
            name='source_ent_name',
            field=models.TextField(blank=True, max_length=255, verbose_name='предприятие - источник'),
        ),
    ]
