# Generated by Django 5.2.6 on 2025-11-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0030_remove_stockentrymain_source_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockEntryComment',
        ),
    ]
