# Generated by Django 5.2.6 on 2025-11-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0031_delete_stockentrycomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEntityInfo',
            fields=[
                ('guid', models.UUIDField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'хозяйствующий субъект (инфо)',
                'verbose_name_plural': 'хозяйствующие субъекты (инфо)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseInfo',
            fields=[
                ('guid', models.UUIDField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='адрес')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'предприятие (инфо)',
                'verbose_name_plural': 'предприятия (инфо)',
                'ordering': ['name'],
            },
        ),
    ]
