# Generated by Django 5.2.6 on 2025-11-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0032_businessentityinfo_enterpriseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='vet_document_last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последнее обновление вет. документов'),
        ),
        migrations.CreateModel(
            name='VetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, unique=True)),
                ('issue_date', models.DateField(verbose_name='дата оформления')),
                ('vetd_form', models.CharField(choices=[('CERTCU1', 'Форма 1 ветеринарного сертификата ТС'), ('LIC1', 'Форма 1 ветеринарного свидетельства'), ('CERTCU2', 'Форма 2 ветеринарного сертификата ТС'), ('LIC2', 'Форма 2 ветеринарного свидетельства'), ('CERTCU3', 'Форма 3 ветеринарного сертификата ТС'), ('LIC3', 'Форма 3 ветеринарного свидетельства'), ('NOTE4', 'Форма 4 ветеринарной справки'), ('CERT5I', 'Форма 5i ветеринарного сертификата'), ('CERT61', 'Форма 6.1 ветеринарного сертификата'), ('CERT62', 'Форма 6.2 ветеринарного сертификата'), ('CERT63', 'Форма 6.3 ветеринарного сертификата'), ('PRODUCTIVE', 'Форма производственного ветеринарного сертификата')], max_length=10, verbose_name='форма')),
                ('vetd_type', models.CharField(choices=[('INCOMING', 'Входящий ВСД'), ('OUTGOING', 'Исходящий ВСД'), ('PRODUCTIVE', 'Производственный ВСД'), ('RETURNABLE', 'Возвратный ВСД'), ('TRANSPORT', 'Транспортный ВСД')], max_length=10, verbose_name='тип')),
                ('vetd_status', models.CharField(choices=[('CONFIRMED', 'Оформлен'), ('WITHDRAWN', 'Аннулирован'), ('UTILIZED', 'Погашен'), ('FINALIZED', 'Закрыт')], max_length=10, verbose_name='статус')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='закрыт')),
                ('date_updated', models.DateTimeField(blank=True, null=True, verbose_name='дата изменения статуса')),
                ('status_change', models.TextField(blank=True, verbose_name='информация об изменении статуса')),
                ('consignor_be_guid', models.UUIDField(blank=True, null=True)),
                ('consignor_ent_guid', models.UUIDField(blank=True, null=True)),
                ('consignee_be_guid', models.UUIDField(blank=True, null=True)),
                ('consignee_ent_guid', models.UUIDField(blank=True, null=True)),
                ('producer_be_guid', models.UUIDField(blank=True, null=True)),
                ('producer_ent_guid', models.UUIDField(blank=True, null=True)),
                ('product_type', models.IntegerField(choices=[(1, 'Мясо и мясопродукты'), (2, 'Корма и кормовые добавки'), (3, 'Живые животные'), (4, 'Лекарственные средства'), (5, 'Пищевые продукты'), (6, 'Непищевые продукты и другое'), (7, 'Рыба и морепродукты'), (8, 'Продукция, не требующая разрешения')], verbose_name='тип продукции')),
                ('product_guid', models.UUIDField(blank=True, null=True, verbose_name='продукция (GUID)')),
                ('subproduct_guid', models.UUIDField(blank=True, null=True, verbose_name='вид продукции (GUID)')),
                ('product_item_guid', models.UUIDField(blank=True, null=True, verbose_name='наименование продукции (GUID)')),
                ('product_item_name', models.CharField(max_length=255, verbose_name='наименование продукции')),
                ('volume', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='объем')),
                ('date_produced_1', models.CharField(max_length=16, verbose_name='дата производства 1')),
                ('date_produced_2', models.CharField(blank=True, max_length=16, verbose_name='дата производства 2')),
                ('date_produced', models.DateTimeField(verbose_name='дата производства')),
                ('date_expiry_1', models.CharField(max_length=16, verbose_name='срок годности 1')),
                ('date_expiry_2', models.CharField(blank=True, max_length=16, verbose_name='срок годности 2')),
                ('date_expiry', models.DateTimeField(verbose_name='срок годности')),
                ('is_perishable', models.BooleanField(verbose_name='скоропорт')),
                ('origin_country', models.CharField(blank=True, max_length=255, null=True, verbose_name='страна происхождения')),
                ('producer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='наименование производителя')),
                ('consignee_enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignee_vetd_set', to='vetis_api.enterprise', verbose_name='предприятие-получатель')),
                ('consignor_enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignor_vetd_set', to='vetis_api.enterprise', verbose_name='предприятие-отправитель')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vetis_api.enterprise', verbose_name='предприятие')),
                ('producer_enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer_vetd_set', to='vetis_api.enterprise', verbose_name='предприятие-получатель')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vetis_api.product', verbose_name='продукция')),
                ('product_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vetis_api.productitem', verbose_name='наименование продукции (справочник)')),
                ('subproduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vetis_api.subproduct', verbose_name='вид продукции')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vetis_api.unit', verbose_name='ЕИ')),
            ],
            options={
                'verbose_name': 'ветеринарный документ',
                'verbose_name_plural': 'ветеринарные документы',
                'ordering': ['-date_updated'],
            },
        ),
    ]
