# Generated by Django 5.2.6 on 2025-11-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0033_enterprise_vet_document_last_updated_vetdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='vet_document_last_updated',
            new_name='vet_documents_last_updated',
        ),
    ]
