# Generated by Django 5.2.6 on 2025-11-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0034_rename_vet_document_last_updated_enterprise_vet_documents_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetdocument',
            name='consignee_enterprise',
        ),
        migrations.RemoveField(
            model_name='vetdocument',
            name='consignor_enterprise',
        ),
        migrations.RemoveField(
            model_name='vetdocument',
            name='producer_enterprise',
        ),
        migrations.AddField(
            model_name='vetdocument',
            name='consignee_be_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='наименование субъекта-получателя'),
        ),
        migrations.AddField(
            model_name='vetdocument',
            name='consignee_ent_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='наименование предприятия-получателя'),
        ),
        migrations.AddField(
            model_name='vetdocument',
            name='consignor_be_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='наименование субъекта-отправителя'),
        ),
        migrations.AddField(
            model_name='vetdocument',
            name='consignor_ent_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='наименование предприятия-отправителя'),
        ),
        migrations.AddField(
            model_name='vetdocument',
            name='producer_be_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='наименование субъекта-производителя'),
        ),
        migrations.AddField(
            model_name='vetdocument',
            name='producer_ent_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='наименование предприятия-производителя'),
        ),
        migrations.AlterField(
            model_name='vetdocument',
            name='consignee_be_guid',
            field=models.UUIDField(blank=True, null=True, verbose_name='GUID субъекта-получателя'),
        ),
        migrations.AlterField(
            model_name='vetdocument',
            name='consignee_ent_guid',
            field=models.UUIDField(blank=True, null=True, verbose_name='GUID предприятия-получателя'),
        ),
        migrations.AlterField(
            model_name='vetdocument',
            name='consignor_be_guid',
            field=models.UUIDField(blank=True, null=True, verbose_name='GUID субъекта-отправителя'),
        ),
        migrations.AlterField(
            model_name='vetdocument',
            name='consignor_ent_guid',
            field=models.UUIDField(blank=True, null=True, verbose_name='GUID предприятия-отправителя'),
        ),
        migrations.AlterField(
            model_name='vetdocument',
            name='producer_be_guid',
            field=models.UUIDField(blank=True, null=True, verbose_name='GUID субъекта-производителя'),
        ),
        migrations.AlterField(
            model_name='vetdocument',
            name='producer_ent_guid',
            field=models.UUIDField(blank=True, null=True, verbose_name='GUID предприятия-производителя'),
        ),
    ]
