# Generated by Django 5.2.6 on 2025-11-17 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0035_remove_vetdocument_consignee_enterprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseinfo',
            name='business_entity',
            field=models.ForeignKey(default='29bad9e0-c666-4703-b30d-f54b5e895011', on_delete=django.db.models.deletion.PROTECT, to='vetis_api.businessentityinfo', verbose_name='хозяйствующий субъект'),
            preserve_default=False,
        ),
    ]
