# Generated by Django 5.2.6 on 2025-11-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0036_enterpriseinfo_business_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseinfo',
            name='business_entity',
        ),
        migrations.RemoveField(
            model_name='vetdocument',
            name='enterprise',
        ),
        migrations.AlterField(
            model_name='vetdocument',
            name='consignee_ent_guid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='GUID предприятия-получателя'),
        ),
        migrations.AlterField(
            model_name='vetdocument',
            name='consignor_ent_guid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='GUID предприятия-отправителя'),
        ),
        migrations.AlterField(
            model_name='vetdocument',
            name='producer_ent_guid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='GUID предприятия-производителя'),
        ),
    ]
