# Generated by Django 5.2.6 on 2025-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0037_remove_enterpriseinfo_business_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='guid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stockentrymain',
            name='initial_status',
            field=models.IntegerField(blank=True, choices=[(100, 'Запись создана'), (101, 'Гашение ВС (импорт)'), (102, 'Гашение ВСД'), (103, 'Производство'), (104, 'Справка о здоровье дойных животных'), (105, 'Аннулирование ВСД или транзакции'), (106, 'Гашение бумажного ВСД'), (110, 'Объединение'), (120, 'Разделение'), (200, 'Внесены изменения'), (201, 'Запись аннулирована'), (202, 'Списание'), (203, 'Редактирование производства'), (204, 'Заключение по результатам ВСЭ'), (230, 'Обновление в результате присоединения'), (231, 'Обновление в результате присоединения'), (240, 'Обновление в результате отделения'), (250, 'Восстановление после удаления'), (260, 'Пометка на удаление'), (300, 'Перемещение в другую группу'), (400, 'Запись удалена'), (410, 'Удаление в результате объединения'), (420, 'Удаление в результате разделения'), (430, 'Удаление в результате присоединения')], null=True, verbose_name='статус'),
        ),
    ]
