# Generated by Django 5.2.6 on 2025-11-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetis_api', '0038_alter_productitem_guid_alter_productitem_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssortGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
            ],
            options={
                'verbose_name': 'ассортиментная группа',
                'verbose_name_plural': 'ассортиментные группы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vetis_api.product', verbose_name='продукция'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='subproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vetis_api.subproduct', verbose_name='вид продукции'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='assort_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vetis_api.assortgroup', verbose_name='ассортиментная группа'),
        ),
    ]
